var mongoose = require('mongoose');

var packageSchema = mongoose.Schema({
  architecture: [String],
  author: String,
  average_rating: Number,
  bayesian_average: {type: Number, index: true},
  categories: {type: [String], index: true},
  changelog: String,
  channels: [String],
  cloudinary_url: String,
  company: String,
  description: String,
  download: String,
  downloads: {},
  filesize: String,
  framework: [String],
  icon_fetch_date: Number,
  icon_filename: String,
  icon_hash: String,
  icon: String,
  keywords: [String],
  last_updated: String,
  license: String,
  monthly_popularity: Number,
  name: {type: String, index: true},
  num_reviews: Number,
  points: {type: Number, index: true},
  prices: {},
  published_date: String,
  release: [String],
  revision: String,
  screenshot: String,
  screenshots: [String],
  status: String,
  support: String,
  tagline: String,
  takedown: Boolean,
  terms: String,
  title: String,
  total_rating: Number,
  translations: {},
  type: String,
  types: {type: [String], index: true},
  ubuntu_id: String,
  url: String,
  version: String,
  videos: [String],
  webapp_inject: Boolean,
  website: String,
});

packageSchema.index({
  title: 'text',
  description: 'text',
  keywords: 'text',
  author: 'text',
  company: 'text',
},
{
  weights: {
    title: 10,
    description: 5,
    keywords: 3,
    author: 1,
    company: 1,
  },
  name: 'searchIndex',
});

var Package = mongoose.model('Package', packageSchema);

exports.Package = Package;
