#!/bin/bash

set -e

echo "Deploying code"
git --work-tree=/srv/uappexplorer --git-dir=/srv/repo/uappexplorer.git checkout -f

echo "Running npm install"
cd /srv/uappexplorer/
npm install

echo "Builing frontend"
source /srv/uappexplorer/deploy/env.sh
export NODE_ENV=""  # Needed to install dev dependencies
cd /srv/uappexplorer/www/
npm install
export NODE_ENV="production"
gulp build

# Copy dist to a separate directory, this way when we clean out dist to rebuild it doesn't take the site down for several minutes
rm -rf ./production
cp -r ./dist ./production

echo "Restarting api"
systemctl restart uappexplorer-api
